version: '3.1'

services:
  tasks-app:
    build:
      context: .
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - mysql
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
  
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: developer
      MYSQL_PASSWORD: Pass1234565
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - "9000:80"
    depends_on:
      - mysql

volumes:
  mysql_data: